version: '3'

services:
    astrosports.web:
        image: elitonluiz1989/php

        container_name: astrosports.web

        working_dir: /var/wwww/html/

        ports:
            - "80:80"
            - "9000:9000"

        depends_on:
            - astrosports.mysql

        volumes:
            - .:/var/wwww/html/
            - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf

        command: ["wait-for-it", "astrosports.mysql:3306 -t 0", "--", "sh", "./docker/entrypoint.sh"]

        #environment:
          #xDebug configs for 'development' environment
         #   - XDEBUG_INSTALL="true"
         #   - XDEBUG_CONFIG="remote_host=localhost"
         #   - XDEBUG_REMOTE_ENABLE=on
         #   - XDEBUG_REMOTE_AUTOSTART=on
         #   - XDEBUG_REMOTE_CONNECT_BACK=off
         #   - XDEBUG_REMOTE_HANDLER=dbgp
         #   - XDEBUG_PROFILER_ENABLE=1
         #   - XDEBUG_PROFILER_OUTPUT_DIR=/tmp/www/html
         #   - XDEBUG_REMOTE_PORT=9000
         #   - XDEBUGINI_PATH=/usr/local/etc/php/conf.d/xdebug.ini
         #   - PHP_IDE_CONFIG="serverName=Test"

    astrosports.mysql:
        image: mysql:latest

        container_name: astrosports.mysql

        ports:
          - "3306:3306"

        environment:
          - MYSQL_ROOT_PASSWORD=5119191413
          - MYSQL_DATABASE=astrosports
          - MYSQL_USER=elitonluiz
          - MYSQL_PASSWORD=5119191413