version: '3'

services:
    astrosports:
        image: elitonluiz1989/php-devenv

        container_name: astrosports

        working_dir: /var/www/html/

        ports:
            -   "80:80"
            -   "3000:3000"

        links:
            - astrosports_mysql

        volumes:
            -   .:/var/www/html/
            -   ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf

    astrosports_phpmyadmin:
        image: phpmyadmin/phpmyadmin

        container_name: astrosports_phpmyadmin

        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=astrosports_mysql

        ports:
            - "8080:80"

        depends_on:
            - astrosports_mysql

        volumes:
            - /sessions

    astrosports_mysql:
        image: mysql:5.7

        container_name: astrosports_mysql

        ports:
          - "9090:3306"

        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=astrosports
          - MYSQL_USER=elitonluiz
          - MYSQL_PASSWORD=5119191413

        #volumes:
        #  - ./docker/astrosports.sql:/docker-entrypoint-initdb.d/astrosports.sql