version: '3'

services:
  astrosports:
    image: elitonluiz1989/php-devenv

    container_name: astrosports

    working_dir: /var/www/html/

    ports:
      -   "88:80"
      -   "3000:3000"

    links:
      - astrosports.mysql

    volumes:
      - .:/var/www/html/
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf

    environment:
      - APPLICATION_ENV=development
      #xDebug configs for 'development' environment
      #   - XDEBUG_INSTALL="true"
      #   - XDEBUG_CONFIG="remote_host=localhost"
      #   - XDEBUG_REMOTE_ENABLE=on
      #   - XDEBUG_REMOTE_AUTOSTART=on
      #   - XDEBUG_REMOTE_CONNECT_BACK=off
      #   - XDEBUG_REMOTE_HANDLER=dbgp
      #   - XDEBUG_PROFILER_ENABLE=1
      #   - XDEBUG_PROFILER_OUTPUT_DIR=/tmp/www/html
      #   - XDEBUG_REMOTE_PORT=9000
      #   - XDEBUGINI_PATH=/usr/local/etc/php/conf.d/xdebug.ini
      #   - PHP_IDE_CONFIG="serverName=Test"

  astrosports.mysql:
    image: mysql:5.7

    container_name: astrosports.mysql

    ports:
      - "9090:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=5119191413
      - MYSQL_DATABASE=astrosports
      - MYSQL_USER=elitonluiz
      - MYSQL_PASSWORD=5119191413
      #- MYSQL_HOST=127.0.0.1

    volumes:
      - ./docker/database.sql:/docker-entrypoint-initdb.d/database.sql

  astrosports.phpmyadmin:
    image: phpmyadmin/phpmyadmin

    container_name: astrosports.phpmyadmin

    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=astrosports.mysql

    ports:
      - "8080:80"

    depends_on:
      - astrosports.mysql

    volumes:
      - /sessions
