version: '3'

services:
    app:
        image: elitonluiz1989/devenv

        container_name: app

        ports:
            -   "80:80"
            -   "3000:3000"

        links:
            - mysql

        volumes:
            -   .:/app/
            -   ./docker/.bashrc:/root/.bashrc
            -   ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin

        container_name: phpmyadmin

        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql

        restart: always

        ports:
            - "8080:80"

        depends_on:
            - mysql

        volumes:
            - /sessions

    mysql:
        image: mysql

        container_name: mysql

        ports:
          - "9090:3306"

        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=astrosports
          - MYSQL_USER=elitonluiz
          - MYSQL_PASSWORD=5119191413
